/**
 * generated by Xtext
 */
package org.xtext.idm.projet.serializer;

import org.xtext.idm.projet.serializer.AbstractStateMachineSemanticSequencer;

@SuppressWarnings("all")
public class StateMachineSemanticSequencer extends AbstractStateMachineSemanticSequencer {
}
