/**
 * generated by Xtext
 */
package org.xtext.idm.projet.serializer;

import org.xtext.idm.projet.serializer.AbstractStateMachineSyntacticSequencer;

@SuppressWarnings("all")
public class StateMachineSyntacticSequencer extends AbstractStateMachineSyntacticSequencer {
}
