/*
 * generated by Xtext
 */
package org.xtext.idm.projet;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StateMachineRuntimeModule extends org.xtext.idm.projet.AbstractStateMachineRuntimeModule {

}
