/*
 * generated by Xtext
 */
package org.xtext.idm.projet.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StateMachineUiModule extends org.xtext.idm.projet.ui.AbstractStateMachineUiModule {
	public StateMachineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
