/*
 * generated by Xtext
 */
package org.xtext.idm.projet.ui.contentassist

import org.xtext.idm.projet.ui.contentassist.AbstractStateMachineProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class StateMachineProposalProvider extends AbstractStateMachineProposalProvider {
}
