/*
 * generated by Xtext
 */
package org.xtext.idm.projet;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class StateMachineUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.idm.projet.ui.internal.StateMachineActivator.getInstance().getInjector("org.xtext.idm.projet.StateMachine");
	}
	
}
